package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "safety_layer_proto",
    deps = [
        ":safety_layer_proto_lib",
    ],
)

proto_library(
    name = "safety_layer_proto_lib",
    srcs = [
        "frame.proto",
    ],
)
